In [34]:
import pyart
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [35]:
def calculate_avg_reflectivity(reflectivity):
    # Calculate the percentage of each reflectivity value in each of 8 ranges
    # Count the reflectivity value smaller than 30
    reflectivity_smaller_than_0 = len([ele for ele in reflectivity if ele < 0]) / len(reflectivity)
    reflectivity_0_to_5         = len([ele for ele in reflectivity if 0 <= ele < 5]) / len(reflectivity)
    reflectivity_5_to_10        = len([ele for ele in reflectivity if 5 <= ele < 10]) / len(reflectivity)
    reflectivity_10_to_15       = len([ele for ele in reflectivity if 10 <= ele < 15]) / len(reflectivity)
    reflectivity_15_to_20       = len([ele for ele in reflectivity if 15 <= ele < 20]) / len(reflectivity)
    reflectivity_20_to_25       = len([ele for ele in reflectivity if 20 <= ele < 25]) / len(reflectivity)
    reflectivity_25_to_30       = len([ele for ele in reflectivity if 25 <= ele < 30]) / len(reflectivity)
    reflectivity_30_to_35       = len([ele for ele in reflectivity if 30 <= ele < 35]) / len(reflectivity)
    reflectivity_35_to_40       = len([ele for ele in reflectivity if 35 <= ele < 40]) / len(reflectivity)
    reflectivity_40_to_45       = len([ele for ele in reflectivity if 40 <= ele < 45]) / len(reflectivity)
    reflectivity_45_to_50       = len([ele for ele in reflectivity if 45 <= ele < 50]) / len(reflectivity)
    reflectivity_50_to_55       = len([ele for ele in reflectivity if 50 <= ele < 55]) / len(reflectivity)
    reflectivity_55_to_60       = len([ele for ele in reflectivity if 55 <= ele < 60]) / len(reflectivity)
    reflectivity_bigger_than_60 = len([ele for ele in reflectivity if ele >= 60]) / len(reflectivity)
    
    weight_set = [pow(10, 100 * (1 - reflectivity_smaller_than_0)),
                  pow(10, 100 * (1 - reflectivity_0_to_5)),
                  pow(10, 100 * (1 - reflectivity_5_to_10)),
                  pow(10, 100 * (1 - reflectivity_10_to_15)),
                  pow(10, 100 * (1 - reflectivity_15_to_20)),
                  pow(10, 100 * (1 - reflectivity_20_to_25)),
                  pow(10, 100 * (1 - reflectivity_25_to_30)), 
                  pow(10, 100 * (1 - reflectivity_30_to_35)),
                  pow(10, 100 * (1 - reflectivity_35_to_40)),
                  pow(10, 100 * (1 - reflectivity_40_to_45)),
                  pow(10, 100 * (1 - reflectivity_45_to_50)), 
                  pow(10, 100 * (1 - reflectivity_50_to_55)),
                  pow(10, 100 * (1 - reflectivity_55_to_60)),
                  pow(10, 100 * (1 - reflectivity_bigger_than_60))]

    # print(weight_set)

    weights = []
    for ele in reflectivity:
        if ele < 0:
            weights += [weight_set[0]]
        elif 0 <= ele < 5:
            weights += [weight_set[1]]
        elif 5 <= ele < 10:
            weights += [weight_set[2]]
        elif 10 <= ele < 15:
            weights += [weight_set[3]]
        elif 15 <= ele < 20:
            weights += [weight_set[4]]
        elif 20 <= ele < 25:
            weights += [weight_set[5]]
        elif 25 <= ele < 30:
            weights += [weight_set[6]]
        elif 30 <= ele < 35:
            weights += [weight_set[7]]
        elif 35 <= ele < 40:
            weights += [weight_set[8]]
        elif 40 <= ele < 45:
            weights += [weight_set[9]]
        elif 45 <= ele < 50:
            weights += [weight_set[10]]
        elif 50 <= ele < 55:
            weights += [weight_set[11]]
        elif 55 <= ele < 60:
            weights += [weight_set[12]]
        elif ele >= 60:
            weights += [weight_set[13]]

    avg_reflectivity = np.average(reflectivity, weights=weights)
    if avg_reflectivity < 30:
        label = "clear"
    elif 30 <= avg_reflectivity < 40:
        label = "light_rain"
    elif 40 <= avg_reflectivity < 47.5:
        label = "moderate_rain"
    elif 47.5 <= avg_reflectivity < 55:
        label = "heavy_rain"
    elif avg_reflectivity >= 55:
        label = "very_heavy_rain"
        
    return avg_reflectivity, label

In [36]:
data = pyart.io.read_sigmet("/home/hoang-wsl/Works/Thesis/ai-project3/DatailedLabelSample/NHB230601000008.RAWLGZV")
data.fields['reflectivity']['data'] = data.fields['reflectivity']['data'].astype(np.float16)
            
grid_data = pyart.map.grid_from_radars(data,
            grid_shape=(1, 500, 500),
            grid_limits=((0, 1), (-250000, 250000), (-250000, 250000)),)

In [37]:
longitude = data.longitude['data']
latitude = data.latitude['data']

In [38]:
# Print the longitude and latitude arrays
print("Longitude:", longitude)
print("Latitude:", latitude)

Longitude: [106.72833329]
Latitude: [10.65961009]


In [67]:
get_gate_arr = np.array(data.get_gate_lat_lon_alt(sweep=0))
print(get_gate_arr.shape)
latitude = get_gate_arr[0]
longitude = get_gate_arr[1]
altitude = get_gate_arr[2]

(3, 309, 500)


In [69]:
print(latitude.shape)
print(latitude)

(309, 500)
[[10.65960979 10.66500568 10.67040062 ... 13.33917141 13.34455585
  13.34994221]
 [10.65960979 10.66500473 10.67039967 ... 13.33882618 13.34420967
  13.34959507]
 [10.65960979 10.66500282 10.67039585 ... 13.33783054 13.34321308
  13.34859562]
 ...
 [10.65960979 10.66499901 10.67038822 ... 13.33584023 13.34121895
  13.34659672]
 [10.65960979 10.66500282 10.6703949  ... 13.3377037  13.34308529
  13.34846783]
 [10.65960979 10.66500473 10.67039967 ... 13.33886337 13.34424877
  13.34963322]]


In [70]:
print(longitude.shape)
print(longitude)

(309, 500)
[[106.72832489 106.72836304 106.72839355 ... 106.74534607 106.74537659
  106.74542236]
 [106.72832489 106.72842407 106.72852325 ... 106.7784729  106.77857208
  106.77867889]
 [106.72832489 106.728508   106.72868347 ... 106.81950378 106.81968689
  106.81987   ]
 ...
 [106.72832489 106.72805023 106.72777557 ... 106.59153748 106.59125519
  106.59098053]
 [106.72832489 106.72814178 106.72795868 ... 106.63623047 106.63603973
  106.63585663]
 [106.72832489 106.72823334 106.72814941 ... 106.68345642 106.6833725
  106.68327332]]


In [71]:
print(altitude.shape)
print(altitude)

(309, 500)
[[  10.   15.   21. ... 8199. 8226. 8253.]
 [  10.   15.   21. ... 8070. 8097. 8124.]
 [  10.   15.   20. ... 7970. 7997. 8023.]
 ...
 [  10.   15.   22. ... 8298. 8326. 8353.]
 [  10.   15.   21. ... 8213. 8240. 8267.]
 [  10.   15.   21. ... 8199. 8226. 8253.]]
