In [17]:
import pyart
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
def calculate_avg_reflectivity(reflectivity):
    # Calculate the percentage of each reflectivity value in each of 8 ranges
    # Count the reflectivity value smaller than 30
    reflectivity_smaller_than_0 = len([ele for ele in reflectivity if ele < 0]) / len(reflectivity)
    reflectivity_0_to_5         = len([ele for ele in reflectivity if 0 <= ele < 5]) / len(reflectivity)
    reflectivity_5_to_10        = len([ele for ele in reflectivity if 5 <= ele < 10]) / len(reflectivity)
    reflectivity_10_to_15       = len([ele for ele in reflectivity if 10 <= ele < 15]) / len(reflectivity)
    reflectivity_15_to_20       = len([ele for ele in reflectivity if 15 <= ele < 20]) / len(reflectivity)
    reflectivity_20_to_25       = len([ele for ele in reflectivity if 20 <= ele < 25]) / len(reflectivity)
    reflectivity_25_to_30       = len([ele for ele in reflectivity if 25 <= ele < 30]) / len(reflectivity)
    reflectivity_30_to_35       = len([ele for ele in reflectivity if 30 <= ele < 35]) / len(reflectivity)
    reflectivity_35_to_40       = len([ele for ele in reflectivity if 35 <= ele < 40]) / len(reflectivity)
    reflectivity_40_to_45       = len([ele for ele in reflectivity if 40 <= ele < 45]) / len(reflectivity)
    reflectivity_45_to_50       = len([ele for ele in reflectivity if 45 <= ele < 50]) / len(reflectivity)
    reflectivity_50_to_55       = len([ele for ele in reflectivity if 50 <= ele < 55]) / len(reflectivity)
    reflectivity_55_to_60       = len([ele for ele in reflectivity if 55 <= ele < 60]) / len(reflectivity)
    reflectivity_bigger_than_60 = len([ele for ele in reflectivity if ele >= 60]) / len(reflectivity)
    
    weight_set = [pow(10, 100 * (1 - reflectivity_smaller_than_0)),
                  pow(10, 100 * (1 - reflectivity_0_to_5)),
                  pow(10, 100 * (1 - reflectivity_5_to_10)),
                  pow(10, 100 * (1 - reflectivity_10_to_15)),
                  pow(10, 100 * (1 - reflectivity_15_to_20)),
                  pow(10, 100 * (1 - reflectivity_20_to_25)),
                  pow(10, 100 * (1 - reflectivity_25_to_30)), 
                  pow(10, 100 * (1 - reflectivity_30_to_35)),
                  pow(10, 100 * (1 - reflectivity_35_to_40)),
                  pow(10, 100 * (1 - reflectivity_40_to_45)),
                  pow(10, 100 * (1 - reflectivity_45_to_50)), 
                  pow(10, 100 * (1 - reflectivity_50_to_55)),
                  pow(10, 100 * (1 - reflectivity_55_to_60)),
                  pow(10, 100 * (1 - reflectivity_bigger_than_60))]

    # print(weight_set)

    weights = []
    for ele in reflectivity:
        if ele < 0:
            weights += [weight_set[0]]
        elif 0 <= ele < 5:
            weights += [weight_set[1]]
        elif 5 <= ele < 10:
            weights += [weight_set[2]]
        elif 10 <= ele < 15:
            weights += [weight_set[3]]
        elif 15 <= ele < 20:
            weights += [weight_set[4]]
        elif 20 <= ele < 25:
            weights += [weight_set[5]]
        elif 25 <= ele < 30:
            weights += [weight_set[6]]
        elif 30 <= ele < 35:
            weights += [weight_set[7]]
        elif 35 <= ele < 40:
            weights += [weight_set[8]]
        elif 40 <= ele < 45:
            weights += [weight_set[9]]
        elif 45 <= ele < 50:
            weights += [weight_set[10]]
        elif 50 <= ele < 55:
            weights += [weight_set[11]]
        elif 55 <= ele < 60:
            weights += [weight_set[12]]
        elif ele >= 60:
            weights += [weight_set[13]]

    avg_reflectivity = np.average(reflectivity, weights=weights)
    if avg_reflectivity < 30:
        label = "clear"
    elif 30 <= avg_reflectivity < 40:
        label = "light_rain"
    elif 40 <= avg_reflectivity < 47.5:
        label = "moderate_rain"
    elif 47.5 <= avg_reflectivity < 55:
        label = "heavy_rain"
    elif avg_reflectivity >= 55:
        label = "very_heavy_rain"
        
    return avg_reflectivity, label

In [19]:
data = pyart.io.read_sigmet("./DatailedLabelSample/NHB230601000008.RAWLGZV")
data.fields['reflectivity']['data'] = data.fields['reflectivity']['data'].astype(np.float16)
            
grid_data = pyart.map.grid_from_radars(data,
            grid_shape=(1, 500, 500),
            grid_limits=((0, 1), (-250000, 250000), (-250000, 250000)),)

In [20]:
longitude = data.longitude['data']
latitude = data.latitude['data']

In [21]:
# Print the longitude and latitude arrays
print("Longitude:", longitude)
print("Latitude:", latitude)

Longitude: [106.72833329]
Latitude: [10.65961009]


In [22]:
get_gate_arr = np.array(data.get_gate_lat_lon_alt(sweep=0))
print(get_gate_arr.shape)
latitude = get_gate_arr[0]
longitude = get_gate_arr[1]
altitude = get_gate_arr[2]

(3, 309, 500)


In [23]:
print(latitude.shape)
print(latitude)

(309, 500)
[[10.65961009 10.6650057  10.67040139 ... 13.33917143 13.34455654
  13.34994222]
 [10.65961009 10.66500493 10.67039985 ... 13.33882639 13.34421076
  13.34959485]
 [10.65961009 10.66500288 10.67039576 ... 13.33783064 13.34321283
  13.34859598]
 ...
 [10.65961009 10.66499912 10.67038823 ... 13.33584089 13.34121897
  13.34659755]
 [10.65961009 10.66500278 10.67039555 ... 13.33770305 13.3430853
  13.34846786]
 [10.65961009 10.66500508 10.67040017 ... 13.33886371 13.34424838
  13.34963344]]


In [24]:
print(longitude.shape)
print(longitude)

(309, 500)
[[106.72833329 106.72836724 106.7284012  ... 106.74535677 106.74539133
  106.7454259 ]
 [106.72833329 106.7284333  106.72853331 ... 106.77847841 106.77858023
  106.77868206]
 [106.72833329 106.72851513 106.72869697 ... 106.81950762 106.81969275
  106.81987792]
 ...
 [106.72833329 106.72806047 106.72778764 ... 106.59154492 106.59126716
  106.5909894 ]
 [106.72833329 106.72814961 106.72796593 ... 106.63623904 106.63605206
  106.63586505]
 [106.72833329 106.72824381 106.72815432 ... 106.68346682 106.68337573
  106.68328461]]


In [25]:
print(altitude.shape)
print(altitude)

(309, 500)
[[  10.   15.   21. ... 8199. 8226. 8253.]
 [  10.   15.   21. ... 8070. 8097. 8124.]
 [  10.   15.   20. ... 7970. 7997. 8023.]
 ...
 [  10.   15.   22. ... 8298. 8326. 8353.]
 [  10.   15.   21. ... 8213. 8240. 8267.]
 [  10.   15.   21. ... 8199. 8226. 8253.]]
